language: java
key: DISPLAY value:0:0
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
env:
  global:
    - BASEURL=$BASE_URL
    - APITOKEN=$API_TOKEN
    - DELETETOKEN=$DELETE_TOKEN
    - GITHUBTOKEN=$GITHUB_TOKEN
    - BUILDNUMBER=$TRAVIS_BUILD_NUMBER
    - MOCKTESTS=$MOCK_TESTS
script:
  - mvn clean test -Dbase.url=$BASEURL -Dapi.token=$APITOKEN -Ddelete.token=$DELETETOKEN -Dmock.tests=$MOCKTESTS
before_deploy:
  - mv target/report/conclave_api_test_report.html target/report/conclave_api_test_report_$BUILDNUMBER.html
  - cp target/report/conclave_api_test_report_$BUILDNUMBER.html target/report/index.html
deploy:
  local_dir: target/report
  provider: pages
  skip_cleanup: true
  github_token: $GITHUBTOKEN
  keep_history: true
  verbose: true
  target-branch: gh-pages
  on:
    branch: main
notifications:
  email:
    recipients:
      - amrutha.sireesh@crowncommercial.gov.uk
      - himani.nare@crowncommercial.gov.uk