language: java
install: true
key: DISPLAY value:0:0
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
env:
  global:
    - BASEURL=$BASE_URL
    - APIKEY=$API_KEY
    - GITHUBTOKEN=$GITHUB_TOKEN
    - BUILDNUMBER=$TRAVIS_BUILD_NUMBER
    - GHREF=$GH_REF
    - GITNAME=$GIT_NAME
    - GITEMAIL=$GIT_EMAIL
script:
  - mvn clean test -Dbase.url=$BASEURL -Dapi.key=$APIKEY
before_deploy:
  - mv target/report/conclave_api_test_report.html target/report/conclave_api_test_report_$BUILDNUMBER.html
  - cp target/report/conclave_api_test_report_$BUILDNUMBER.html target/report/index.html
after_failure:
  local_dir: target/report
  provider: pages
  skip_cleanup: true
  github_token: $GITHUBTOKEN
  keep_history: true
  verbose: true
  target-branch: gh-pages
  on:
    branch: feature/travisNotification

#after_script:
#  - ./deploy-gh-pages.sh
notifications:
  email:
    recipients:
      - amrutha.sireesh@crowncommercial.gov.uk