language: java
key: DISPLAY value:0:0
before_install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
env:
  global:
    - BASEURL=$BASE_URL
script:
- mvn clean test -Dbase.url=$BASEURL || echo = 'done'