language: java
key: DISPLAY value:0:0
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
env:
  global:
    - BASEURL=$BASE_URL
    - APIKEY=$API_KEY
    - GITHUBTOKEN=$GITHUB_TOKEN
    - BUILDNUMBER=$TRAVIS_BUILD_NUMBER
script:
  - mvn clean test -Dbase.url=$BASEURL -Dapi.key=$APIKEY || echo "done"
before_deploy:
  - mv target/report target/report_$BUILDNUMBER
  - mv target/report_$BUILDNUMBER/conclave_api_test_report.html target/report_$BUILDNUMBER/conclave_api_test_report_$BUILDNUMBER.html
  - cp target/report_$BUILDNUMBER/conclave_api_test_report_$BUILDNUMBER.html target/report_$BUILDNUMBER/index.html
deploy:
  local_dir: target/report_$BUILDNUMBER
  provider: pages
  skip_cleanup: true
  github_token: $GITHUBTOKEN
  keep_history: true
  on:
    branch: feature/FixErrorScenariosTests