language: java
key: DISPLAY value:0:0
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
env:
  global:
    - BASEURL=$BASE_URL
    - APIKEY=$API_KEY
script:
  - mvn clean test -Dbase.url=$BASEURL -Dapi.key=$APIKEY || echo "done"
before_deploy:
  - cp target/report/conclave_api_test_report.html target/report/index.html
deploy:
    local_dir: target/report/
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: feature/FixSchemeNamesTest
