language: java
key: DISPLAY value:0:0
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
env:
  global:
    - CIIBASEURL=$CII_BASE_URL
    - CIIMOCKBASEURL=$CII_MOCK_BASE_URL
    - CONCLAVEBASEURL=$CONCLAVE_BASE_URL
    - CONCLAVELOGINURL=$CONCLAVE_LOGIN_URL
    - LOGINTOKEN=$LOGIN_TOKEN
    - AUTH0URL=$AUTH0_URL
    - APITOKEN=$API_TOKEN
    - MIGRATIONTOKEN=$MIGRATION_TOKEN
    - DELETETOKEN=$DELETE_TOKEN
    - CLIENTID=$CLIENT_ID
    - CLIENTSECRET=$CLIENT_SECRET
    - GITHUBTOKEN=$GITHUB_TOKEN
    - BUILDNUMBER=$TRAVIS_BUILD_NUMBER
    - MOCKTESTS=$MOCK_TESTS
script:
  - mvn clean test -Dmigration.token=$MIGRATIONTOKEN -Dcii.base.url=$CIIBASEURL -Dconclave.base.url=$CONCLAVEBASEURL -Dcii.mock.base.url=$CIIMOCKBASEURL -Dlogin.token=$LOGINTOKEN -Dconclave.login.url=$CONCLAVELOGINURL -Dauth0.url=$AUTH0URL -Dapi.token=$APITOKEN -Ddelete.token=$DELETETOKEN -Dclient.id=$CLIENTID -Dclient.secret=$CLIENTSECRET -Dmock.tests=$MOCKTESTS
before_deploy:
  - mv target/report/conclave_api_test_report.html target/report/conclave_api_test_report_$BUILDNUMBER.html
  - cp target/report/conclave_api_test_report_$BUILDNUMBER.html target/report/index.html
deploy:
  local_dir: target/report
  provider: pages
  skip_cleanup: true
  github_token: $GITHUBTOKEN
  keep_history: true
  verbose: true
  target-branch: gh-pages
  on:
    branch: main
notifications:
  email:
    recipients:
      - amrutha.sireesh@crowncommercial.gov.uk
      - himani.nare@crowncommercial.gov.uk